backend:
  name: git-gateway
  branch: master

media_folder: static/imgs
public_folder: /imgs

collections:
  - name: posts
    label: Posts
    format: json
    folder: static/posts/
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image'}
      - name: tag
        label: Tag
        widget: relation
        collection: "tags"
        searchFields: ['tag_title']
        valueField: "tag_title"
        multiple: true
      - name: author
        label: Author
        widget: relation
        collection: "authors"
        searchFields: ['author_name']
        valueField: "author_name"
        multiple: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: tags
    label: Tags
    folder: static/tags/
    create: true
    slug: '{{tag_title}}'
    identifier_field: tag_title
    fields:
      - { label: 'Title', name: 'tag_title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: authors
    label: Authors
    folder: static/authors/
    create: true
    slug: '{{author_name}}'
    identifier_field: author_name
    fields:
      - { label: 'Name', name: 'author_name', widget: 'string' }
      - { label: 'Bio', name: 'author_description', widget: 'markdown'}
      - { label: 'Photo', name: 'author_photo', widget: 'image'}
